---
title: "Exp-2"
output: html_document
---

```{r setup, include=FALSE}
library(plyr)
library(ggplot2)
library(ez)
library(sfsmisc)
library(gtools)
library(zoo)
library(pracma)
library(ggsignif)
library(magrittr)
library(gganimate)
library(ggsci)
library(rstatix)
library(bruceR)
library(RColorBrewer)
library(Metrics)
```

```{r read the data and pre-process, include=FALSE}
subs <- dir(path = "./Exp-2")
subs <- mixedsort(subs)
trialnum <- 110
datall <- data.frame()
Path_X <- data.frame()
Path_Time <- data.frame()

for (i in c(1:length(subs)))
{
  dat <- read.table(paste0("./Exp-2",subs[i]), header = FALSE, sep = ";", na.strings = "NA", dec = ".", strip.white = TRUE)
  dat <- dat[,1:7]
  dat <- cbind(rep(i,nrow(dat)),dat)
  names(dat) <- c("Sub","Trial","Time","Position","Direction","Choice","X","Y")
  dat$X[which(dat$Trial%%2==0)] <- (dat$X[which(dat$Trial%%2==0)]-700)*(-1)
  dat$Y[which(dat$Trial%%2==0)] <- dat$Y[which(dat$Trial%%2==0)]*(-1)
  for (j in 1:trialnum) 
  {
    subdat <- subset(dat,Trial==j)
    
    # add the pre-processed data to the data frame
    datall <- rbind(datall,subdat)
    
    # change the position that "<0" to ">0" (position=-100 is the same as position=100)
    if (subdat$Position[1]<0)
    {
      subdat$Position <- (-1) * subdat$Position
      subdat$Y <- (-1) * subdat$Y
      
      if (subdat$Direction[1]==0){
        subdat$Direction <- 1
      }else{
        subdat$Direction <- 0
      }
    }
    
    # do the linear interpolation of the path
    subdat_revised <- subdat
    subdat_revised <- rbind(list(subdat[1,1],subdat[1,2],0,subdat_revised[1,4],subdat_revised[1,5],subdat_revised[1,6],0,0),subdat_revised)
    subdat_revised <- subdat_revised[!duplicated(subdat_revised$X),]
    subdat_revised <- arrange(subdat_revised,X)
    subdat_revised <- na.omit(subdat_revised)
    
    # get the Path_X
    x_step <- seq(1,670,len = 670)
    subdat_revised_x <- subdat_revised
    y_revised <- interp1(subdat_revised_x$X,subdat_revised_x$Y,x_step,'linear')
    subdat_revised_x_final <- data.frame("Sub"=rep(i,670),"Trial"=rep(j,670),"Position"=rep(subdat_revised_x$Position[1],670),"Direction"=rep(subdat_revised_x$Direction[1],670),"Choice"=rep(subdat_revised_x$Choice[1],670))
    subdat_revised_x_final <- cbind(subdat_revised_x_final,x_step,y_revised)
    names(subdat_revised_x_final) <- c("Sub","Trial","Position","Direction","Choice","X","Y")
    
    # reset the start point of path to (1,0)
    subdat_revised_x_final$Y <- subdat_revised_x_final$Y - subdat_revised_x_final$Y[1]
    
    # get the Sub_Direction in this trial (0 means left, 1 means right)
    subdat_revised_x_final <- cbind(subdat_revised_x_final,rep(0,nrow(subdat_revised_x_final)))
    names(subdat_revised_x_final) <- c("Sub","Trial","Position","Avatar_Direction","Choice","X","Y","Sub_Direction")
    
    if (subdat_revised_x_final$Y[351]>subdat_revised_x_final$Position[1]){
      subdat_revised_x_final$Sub_Direction <- 1
    }
    
    Path_X <- rbind(Path_X,subdat_revised_x_final[,c(1:4,6:8)])
    print(paste("Sub",i,"Trial",j,sep = "-"))
  }
}

Path_X_subjectfinal <- ddply(Path_X,c("Sub","Position","Avatar_Direction","Sub_Direction","X"),summarise,Mean_Y = mean(Y))
Path_X_final <- ddply(Path_X_subjectfinal,c("Position","Avatar_Direction","Sub_Direction","X"),summarise,Y = mean(Mean_Y),SE = (sd(Mean_Y)/sqrt(length(subs))))

```

```{r get the participants path in different condition, include=FALSE}
Path_used_subject <- ddply(Path_X,c("Sub","Position","Sub_Direction","X"),summarise,Mean_Y = mean(Y))
Path_used <- ddply(Path_used_subject,c("Position","Sub_Direction","X"),summarise,Y = mean(Mean_Y),SE = (sd(Mean_Y)/sqrt(length(subs))))
write.csv(Path_used[which(Path_used$Position!=0),1:4],"Exp-2_Path.csv")
```

```{r calculate the subjects' choice and plot, include=FALSE}
datafinal <- data.frame()
for (i in c(1:length(subs))) 
{
  for (j in 1:trialnum) 
  {
    subdat_choice <- subset(Path_X, Sub==i & Trial==j)
    datafinal <- rbind(datafinal,subdat_choice[which(subdat_choice$X==351),])
    print(paste("Sub",i,"Trial",j,sep = "-"))
  }
}
data_choice <- datafinal[,c(1:4,7)]

data_choice_subjectfinal <- ddply(data_choice,c("Sub","Position"),summarise,Mean_P = mean(Sub_Direction))
data_choice_final <- ddply(data_choice_subjectfinal,c("Position"),summarise,P = mean(Mean_P),SE = (sd(Mean_P)/sqrt(length(subs))))

data_choice_final$P <- 1 - data_choice_final$P
ggplot(data = data_choice_final[which(data_choice_final$Position!=0),],aes(x=Position,y=P)) + geom_point(size=2) + geom_line(aes(color="Red"),size=1) + geom_errorbar(aes(ymin=P-SE,ymax=P+SE), width=3,size=1) + ylab("Probability of walking from right") + xlab("The barrier position") + coord_cartesian(ylim=c(0,1)) + scale_x_continuous(breaks=seq(-100,100,20),expand=c(0.1,0.1)) + scale_y_continuous(breaks=seq(0,1,0.2),expand=c(0,0)) + theme_classic() + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.8),
  axis.ticks = element_line(size=0.8),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_text(size=15, colour="black"),
  legend.position = "right",
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm")) + scale_fill_brewer(palette = "Pastel1")
 ggsave("Choice_Line.pdf",width = 15, height = 15,units = "cm")
```

```{r plot the choice in Exp-1 and Exp-2}
data_choice_exp_1 <- read.csv("Choice_Exp-1.csv")
data_choice_exp_1 <- data_choice_exp_1[,2:4]
data_choice_exp_1$P <- 1 - data_choice_exp_1$P
data_choice_exp_2 <- data_choice_final
data_choice_exp_1 <- cbind(data_choice_exp_1,rep("Exp 1",nrow(data_choice_exp_1)))
names(data_choice_exp_1) <- c("Position","P","SE","Exp")
data_choice_exp_2 <- cbind(data_choice_exp_2,rep("Exp 2",nrow(data_choice_exp_2)))
names(data_choice_exp_2) <- c("Position","P","SE","Exp")
data_choice_all <- rbind(data_choice_exp_1,data_choice_exp_2)

data_choice_all$Exp <- as.factor(data_choice_all$Exp)

ggplot(data = data_choice_all[which(data_choice_all$Position!=0),],aes(x=Position,y=P,group=Exp)) + geom_point(aes(color=Exp),size=3) + geom_line(aes(color=Exp),size=1) + geom_errorbar(aes(ymin=P-SE,ymax=P+SE,color=Exp), width=3,size=1) + ylab("Probability of walking from left side") + xlab("The One-way Mirror's position (cm)") + coord_cartesian(ylim=c(0,1)) + scale_x_continuous(breaks=seq(20,100,20),expand=c(0,5)) + scale_y_continuous(breaks=seq(0,1,0.2),expand=c(0.05,0)) + theme_classic() + scale_color_manual(values = brewer.pal(8,"Set2")[1:2]) + scale_shape_manual(values = c(16,17)) + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.8),
  axis.ticks = element_line(size=0.8),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_text(size=15, colour="black"),
  legend.position = "right",
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
ggsave("Comparison_Choice_Line.pdf",width = 15, height = 10,units = "cm")
```

```{r statistic test}
Exp1_subdat <- read.csv("Sub_Choice_Exp-1.csv")
Exp1_subdat <- Exp1_subdat[,2:4]
Exp1_subdat$Mean_P <- 1 - Exp1_subdat$Mean_P
Exp1_subdat <- cbind(Exp1_subdat,rep("Exp1",nrow(Exp1_subdat)))
Exp1_subdat <- Exp1_subdat[which(Exp1_subdat$Position!=0),]
names(Exp1_subdat) <- c("Sub","Position","P","Exp")

Exp2_subdat <- data_choice_subjectfinal[which(data_choice_subjectfinal$Position!=0),]
Exp2_subdat <- cbind(Exp2_subdat,rep("Exp2",nrow(Exp2_subdat)))
Exp2_subdat$Sub <- rep(26:50,each = 5)
names(Exp2_subdat) <- c("Sub","Position","P","Exp")

subject_sta_test <- rbind(Exp1_subdat,Exp2_subdat)
subject_sta_test$Sub <- as.factor(subject_sta_test$Sub)
subject_sta_test$Position <- as.factor(subject_sta_test$Position)
subject_sta_test$Exp <- as.factor(subject_sta_test$Exp)

MANOVA(data = subject_sta_test,
       subID = "Sub",
       dv = "P",
       between = "Exp",
       within = "Position",
       sph.correction = "GG")%>%
  EMMEANS("Position",by = "Exp")
```

```{r plot the path from real data and model fitting}
RealPath <- Path_used[which(Path_used$Position!=0),]
RealPath <- cbind(RealPath,rep("Real",nrow(RealPath)))
names(RealPath) <- c("Position","Direction","X","Y","SE","Type")
ModelPath <- read.csv("Exp-2_Path_Fit.csv",header = FALSE)
ModelPath <- cbind(ModelPath,rep(0,nrow(ModelPath)))
ModelPath <- cbind(ModelPath,rep("Model",nrow(ModelPath)))
names(ModelPath) <- c("Position","Direction","X","Y","SE","Type")
Compare_Path <- rbind(RealPath,ModelPath)
Compare_Path$Position <- as.factor(Compare_Path$Position)
Compare_Path$Direction <- as.factor(Compare_Path$Direction)
Compare_Path$Type <- as.factor(Compare_Path$Type)

ggplot(data=Compare_Path, aes(x=X, y=Y, group = Type)) + geom_ribbon(aes(ymin=Y-SE*1.96,ymax=Y+SE*1.96),alpha=0.3) + geom_line(aes(color=Type,linetype=Type),linewidth=1) + ylab("Y (cm)") + xlab("X (cm)") + facet_wrap(c("Direction","Position"), ncol=5) +  scale_x_continuous(breaks=seq(0, 700, 200),expand=c(0,0)) + scale_y_continuous(breaks=seq(-300, 300, 100),expand=c(0,0)) + coord_fixed(xlim=c(0,700),ylim=c(-300, 300)) + theme_bw() + scale_color_manual(values = c("#2AB88F","#ED756E")) + scale_linetype_manual(values = c("solid","dashed")) + theme(axis.title = element_text(size=20, colour="black"),
  axis.text  = element_text(size=14, colour="black"),
  axis.line = element_line(size=0.1),
  strip.text = element_text(size=14, colour="black"),
  legend.text = element_text(size=20, colour="black", margin = margin(r = 20, unit = "pt")),
  legend.title = element_blank(),
  legend.position = "top",
  axis.ticks = element_line(size=0.3),
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length = unit(-0.1, "cm"),
  legend.key.width = unit(1.5, "cm"),
  panel.grid.major = element_line(colour = NA),
  panel.background = element_rect(fill = "transparent",colour = NA),
  plot.background = element_rect(fill = "transparent",colour = NA),
  panel.grid.minor = element_blank())
ggsave("Fit_Path.pdf",width = 60, height = 54, units = "cm")
```


```{r plot the choice from real data and model fitting in Exp-1 and Exp-2}
RealChoice <- data_choice_all[which(data_choice_all$Position!=0),]
RealChoice <- cbind(RealChoice,rep("Real",nrow(RealChoice)))
names(RealChoice) <- c("Position","P","SE","Exp","Type")

ModelChoice1 <- read.csv("Exp-1_Choice_Fit.csv",header = FALSE)
ModelChoice1 <- cbind(ModelChoice1[,c(1,3)],rep(0,nrow(ModelChoice1)),rep("Exp 1",nrow(ModelChoice1)),rep("Model",nrow(ModelChoice1)))
names(ModelChoice1) <- c("Position","P","SE","Exp","Type")

ModelChoice2 <- read.csv("Exp-2_Choice_Fit.csv",header = FALSE)
ModelChoice2 <- cbind(ModelChoice2[,c(1,3)],rep(0,nrow(ModelChoice2)),rep("Exp 2",nrow(ModelChoice2)),rep("Model",nrow(ModelChoice2)))
names(ModelChoice2) <- c("Position","P","SE","Exp","Type")

ModelChoice <- rbind(ModelChoice1,ModelChoice2)

ChoiceAll <- rbind(RealChoice,ModelChoice)
ChoiceAll$Exp <- as.factor(ChoiceAll$Exp)
ChoiceAll$Type <- factor(ChoiceAll$Type,levels = c("Real","Model"))

ggplot(data = ChoiceAll,aes(x=Position,y=P,group=interaction(Exp,Type))) + geom_point(aes(shape=Type,color=Exp),size=3) + geom_line(aes(color=Exp,linetype=Type),size=1) + geom_ribbon(data = ChoiceAll[which(ChoiceAll$Type=="Real"),],aes(ymin=P-1.96*SE,ymax=P+1.96*SE,fill=Exp), alpha = 0.15) + ylab("Probability of walking from right") + xlab("The One-way Mirror's position (cm)") + coord_cartesian(ylim=c(0,1)) + scale_x_continuous(breaks=seq(20,100,20),expand=c(0,5)) + scale_y_continuous(breaks=seq(0,1,0.2),expand=c(0,0)) + theme_classic() + scale_fill_manual(values = brewer.pal(8,"Set2")[1:2]) + scale_color_manual(values = brewer.pal(8,"Set2")[1:2]) + scale_shape_manual(values = c(16,17)) + scale_linetype_manual(values = c("solid","dashed")) + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.8),
  axis.ticks = element_line(size=0.8),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_text(size=15, colour="black"),
  legend.position = "right",
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
 ggsave("Comparison_Choice.pdf",width = 15, height = 10,units = "cm")
```

```{r plot the choice from model fitting in Exp-1 and Exp-2}
ModelChoice1 <- read.csv("Exp-1_Choice_Fit.csv",header = FALSE)
ModelChoice1 <- cbind(ModelChoice1[,c(1,3)],rep(0,nrow(ModelChoice1)),rep("Exp 1",nrow(ModelChoice1)),rep("Model",nrow(ModelChoice1)))
names(ModelChoice1) <- c("Position","P","SE","Exp","Type")

ModelChoice2 <- read.csv("Exp-2_Choice_Fit.csv",header = FALSE)
ModelChoice2 <- cbind(ModelChoice2[,c(1,3)],rep(0,nrow(ModelChoice2)),rep("Exp 2",nrow(ModelChoice2)),rep("Model",nrow(ModelChoice2)))
names(ModelChoice2) <- c("Position","P","SE","Exp","Type")

ModelChoice <- rbind(ModelChoice1,ModelChoice2)

ModelChoice$Exp <- as.factor(ModelChoice$Exp)

ggplot(data = ModelChoice,aes(x=Position,y=P,group=Exp)) + geom_point(aes(color=Exp),size=3) + geom_line(aes(color=Exp),size=1) + ylab("Probability of walking from right side") + xlab("The One-way Mirror's position (cm)") + coord_cartesian(ylim=c(0,1)) + scale_x_continuous(breaks=seq(20,100,20),expand=c(0,5)) + scale_y_continuous(breaks=seq(0,1,0.2),expand=c(0.05,0)) + theme_classic() + scale_color_manual(values = brewer.pal(8,"Set2")[1:2]) + scale_shape_manual(values = c(16,17)) + theme(axis.title = element_text(size=15, colour="black"),
  axis.text  = element_text(size=15, colour="black"),
  axis.line = element_line(size=0.8),
  axis.ticks = element_line(size=0.8),
  legend.text = element_text(size=15, colour="black"),
  legend.title = element_text(size=15, colour="black"),
  legend.position = "right",
  axis.text.x = element_text(margin=margin(2, 0, 0, 0, "mm")),
  axis.text.y = element_text(margin=margin(0, 2, 0, 0, "mm")),
  axis.ticks.length=unit(-0.1, "cm"))
ggsave("Predicted_Choice_Line.pdf",width = 15, height = 10,units = "cm")
```
